### ISSUE TITLE
Distribute AWS dev credentials

### ISSUE THREAD

**Issue by neolytics** [code-for-nashville/tracker#27]
Add AWS users to account with ec2 access. 

Currently:
Jstaples
jcockhren

**Comment by jcockhren** [comment]
@neolytics updated my username to the correct spellig. ;)

I'll email you my cell # so we can set my password.

**Comment by neolytics** [comment]
Looking at you @jchapin Can we get the AWS master stuff logged into KDB?

@jcockhren My bad :p



Danka!

On Tue, Jan 27, 2015 at 3:11 PM, Jurnell Cockhren <notifications@github.com>
wrote:

> @neolytics <https://github.com/neolytics> updated my username to the
> correct spellig. ;)
>
> I'll email you my cell # so we can set my password.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/code-for-nashville/tracker/issues/27#issuecomment-71728702>
> .
>



-- 
Jon Staples M.S.2

[Data Scientist | NextGxDx | www.nextgxdx.com]

**Comment by jchapin** [comment]
@neolytics, we actually don't have an AWS account setup yet. Not one that I am aware of at least. We do have the debit card and can sign up for one. But we only have $50 in it, so we can't spin much up yet. The MOU from CfA is incoming though, and hopefully we'll have a check to deposit. I'll go ahead and setup the AWS account shortly.

**Comment by jcockhren** [comment]
@jchapin and @neolytics  PING

AWS Account setup and credentials. As discussed at the last management meeting, the ITS servers will be managed solely by the code 4 nashville team. In order to achieve this, I'd like to implement configuration management in order to ensure proper provisioning and hardening of the servers. 

To ensure this task is completed we need to following:

- upgrade our github org to allow for private repos to for the use of storage of our configuration management data. If not, I'd have to use my own resources, which isn't a problem, but putting it under the bridgade's org protects everyone if I ever got hit by a bus.
- We need access to the AWS account. Given @jchapin pending exit, we'll need more than one person will enough access (via IAM) to do the needed things.
- Given we are still within the free tier usage for new accounts, we can use AWS for our master server (for config management). Which would of course also give us access to S3. Again, I can use my own resrouces, but it makes more sense in my opinion to be owned by the brigade.

**Comment by neolytics** [comment]
I believe we are simply waiting for an AWS account to exist at all. @jchapin

Are we eligible to get free private repos through git hub through code for America?

**Comment by jcockhren** [comment]
@jchapin 
Concerning getting private github repos, we can get on the bronze level for **free**: https://github.com/nonprofit

**Comment by jchapin** [comment]
@jcockhren, we'll give that a shot. I'll write them an e-mail and see if we can provide enough information to get upgraded to bronze. We're not a 501(c)3 yet, but I would bet they have some flexibility.

**Comment by jchapin** [comment]
@neolytics @jcockhren credentials are in the KDB, definitely up for Jurnell's suggestion on setting up user specific keys, taking advantage of Amazon's access control solutions for different users.

Free tier for a year starts today.

![screen shot 2015-02-09 at 12 26 23 am](https://cloud.githubusercontent.com/assets/116142/6101937/b4f148b0-aff2-11e4-9442-f9bb4e72b88e.png)

**Comment by jcockhren** [comment]
completed
